// flow-typed signature: f984e2af7b7e3738d08e82701f206360
// flow-typed version: <<STUB>>/babel-plugin-unassert_v^2.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-unassert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-unassert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-unassert/index' {
  declare module.exports: $Exports<'babel-plugin-unassert'>;
}
declare module 'babel-plugin-unassert/index.js' {
  declare module.exports: $Exports<'babel-plugin-unassert'>;
}
