// flow-typed signature: 5a882365ab0030d5790c02b6c85a8dcd
// flow-typed version: <<STUB>>/github-api_v^3.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'github-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'github-api/dist/components/Gist' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/GitHub' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Issue' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Markdown' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Organization' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Project' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/RateLimit' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Repository' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Requestable' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Search' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/Team' {
  declare module.exports: any;
}

declare module 'github-api/dist/components/User' {
  declare module.exports: any;
}

declare module 'github-api/dist/GitHub.bundle' {
  declare module.exports: any;
}

declare module 'github-api/dist/GitHub.bundle.min' {
  declare module.exports: any;
}

declare module 'github-api/dist/GitHub' {
  declare module.exports: any;
}

declare module 'github-api/dist/GitHub.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'github-api/dist/components/Gist.js' {
  declare module.exports: $Exports<'github-api/dist/components/Gist'>;
}
declare module 'github-api/dist/components/GitHub.js' {
  declare module.exports: $Exports<'github-api/dist/components/GitHub'>;
}
declare module 'github-api/dist/components/Issue.js' {
  declare module.exports: $Exports<'github-api/dist/components/Issue'>;
}
declare module 'github-api/dist/components/Markdown.js' {
  declare module.exports: $Exports<'github-api/dist/components/Markdown'>;
}
declare module 'github-api/dist/components/Organization.js' {
  declare module.exports: $Exports<'github-api/dist/components/Organization'>;
}
declare module 'github-api/dist/components/Project.js' {
  declare module.exports: $Exports<'github-api/dist/components/Project'>;
}
declare module 'github-api/dist/components/RateLimit.js' {
  declare module.exports: $Exports<'github-api/dist/components/RateLimit'>;
}
declare module 'github-api/dist/components/Repository.js' {
  declare module.exports: $Exports<'github-api/dist/components/Repository'>;
}
declare module 'github-api/dist/components/Requestable.js' {
  declare module.exports: $Exports<'github-api/dist/components/Requestable'>;
}
declare module 'github-api/dist/components/Search.js' {
  declare module.exports: $Exports<'github-api/dist/components/Search'>;
}
declare module 'github-api/dist/components/Team.js' {
  declare module.exports: $Exports<'github-api/dist/components/Team'>;
}
declare module 'github-api/dist/components/User.js' {
  declare module.exports: $Exports<'github-api/dist/components/User'>;
}
declare module 'github-api/dist/GitHub.bundle.js' {
  declare module.exports: $Exports<'github-api/dist/GitHub.bundle'>;
}
declare module 'github-api/dist/GitHub.bundle.min.js' {
  declare module.exports: $Exports<'github-api/dist/GitHub.bundle.min'>;
}
declare module 'github-api/dist/GitHub.js' {
  declare module.exports: $Exports<'github-api/dist/GitHub'>;
}
declare module 'github-api/dist/GitHub.min.js' {
  declare module.exports: $Exports<'github-api/dist/GitHub.min'>;
}
