// flow-typed signature: 1e1c4fa88b2ce585a755f557f8581de2
// flow-typed version: <<STUB>>/icon-gen_v^1.0.7/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'icon-gen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'icon-gen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'icon-gen/bin/cli-util' {
  declare module.exports: any;
}

declare module 'icon-gen/bin/main' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/favicon-generator' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/icns-generator' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/ico-generator' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/icon-generator' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/logger' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/main' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/png-generator' {
  declare module.exports: any;
}

declare module 'icon-gen/lib/typedef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'icon-gen/bin/cli-util.js' {
  declare module.exports: $Exports<'icon-gen/bin/cli-util'>;
}
declare module 'icon-gen/bin/main.js' {
  declare module.exports: $Exports<'icon-gen/bin/main'>;
}
declare module 'icon-gen/index' {
  declare module.exports: $Exports<'icon-gen'>;
}
declare module 'icon-gen/index.js' {
  declare module.exports: $Exports<'icon-gen'>;
}
declare module 'icon-gen/lib/favicon-generator.js' {
  declare module.exports: $Exports<'icon-gen/lib/favicon-generator'>;
}
declare module 'icon-gen/lib/icns-generator.js' {
  declare module.exports: $Exports<'icon-gen/lib/icns-generator'>;
}
declare module 'icon-gen/lib/ico-generator.js' {
  declare module.exports: $Exports<'icon-gen/lib/ico-generator'>;
}
declare module 'icon-gen/lib/icon-generator.js' {
  declare module.exports: $Exports<'icon-gen/lib/icon-generator'>;
}
declare module 'icon-gen/lib/logger.js' {
  declare module.exports: $Exports<'icon-gen/lib/logger'>;
}
declare module 'icon-gen/lib/main.js' {
  declare module.exports: $Exports<'icon-gen/lib/main'>;
}
declare module 'icon-gen/lib/png-generator.js' {
  declare module.exports: $Exports<'icon-gen/lib/png-generator'>;
}
declare module 'icon-gen/lib/typedef.js' {
  declare module.exports: $Exports<'icon-gen/lib/typedef'>;
}
