// flow-typed signature: 84640d3760eaefbc1289b514cc3b6574
// flow-typed version: <<STUB>>/sillyname_v^0.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sillyname'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sillyname' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sillyname/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sillyname/index' {
  declare module.exports: $Exports<'sillyname'>;
}
declare module 'sillyname/index.js' {
  declare module.exports: $Exports<'sillyname'>;
}
declare module 'sillyname/test/index.js' {
  declare module.exports: $Exports<'sillyname/test/index'>;
}
